/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.toedter.calendar.JDateChooser;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Diseño
 */
public class form1 extends javax.swing.JFrame {

   
  

 

    /**
     * Creates new form form1
     */
    public form1() {
        initComponents();
        datos2();
    }

    
     public static final String SEPARATOR=";";
   public static final String QUOTE="\"";

   
  public void  datos2(){
 

      
      try {
         
          DefaultTableModel model_tabla=new DefaultTableModel();
          
             
          model_tabla.addColumn("nombre");
          model_tabla.addColumn("apellido");
           model_tabla.addColumn("fecha");
           jTable1.setModel(model_tabla);
      BufferedReader br = null;//C:\Users\lbayona\Documents\NetBeansProjects\lecturaarchivodelimitadoporcomas\src\folder
         br =new BufferedReader(new FileReader("C:\\Users\\lbayona\\Documents\\NetBeansProjects\\lecturaarchivodelimitadoporcomas\\src\\folder\\datos.csv"));
         String line = br.readLine();
         while (null!=line) {
            String [] datos = line.split(SEPARATOR);
            //System.out.println(Arrays.toString(fields));
//System.out.print(datos[2]);


 
//if(date1.equals(datos[2])){
 model_tabla.addRow(datos);
 //line = br.readLine();
//}
        
    line = br.readLine();             

}
         
          
            //line = br.readLine();
      } catch (Exception e) {
        System.out.print(e);
      } 
         
  
  }  
   
   
 public void  datos(String fecha){
 

      
      try {
         
          DefaultTableModel model_tabla=new DefaultTableModel();
          
             
          model_tabla.addColumn("nombre");
          model_tabla.addColumn("apellido");
           model_tabla.addColumn("fecha");
           jTable1.setModel(model_tabla);
      BufferedReader br = null;//C:\Users\lbayona\Documents\NetBeansProjects\lecturaarchivodelimitadoporcomas\src\folder
      File fichero = new File("datos.csv");   
      String ruta=  fichero.getAbsolutePath();
      String replaces="src\\folder\\datos.csv";
      
     String reemplasado=  ruta.replace("datos.csv", replaces);
      //System.out.println(reemplasado +" olas");
       
      br =new BufferedReader(new FileReader(reemplasado));
      
        String line = br.readLine();
         while (null!=line) {
            String [] datos = line.split(SEPARATOR);
            //System.out.println(Arrays.toString(fields));
//System.out.print(datos[2]);
//datos.csv

//System.out.println("La ruta del fichero es: " + fichero.getAbsolutePath());
 
if(fecha.equals(datos[2])){
 model_tabla.addRow(datos);
 //line = br.readLine();
}
        
    line = br.readLine();             

}
         
          
            //line = br.readLine();
      } catch (Exception e) {
        System.out.print(e);
      } 
 }   
  
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDateChooser1.setToolTipText("");
        jDateChooser1.setDateFormatString("dd/MM/yyyy");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       //public static  Date  date= JDateChooser.getDate();
      try {
       
       SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
       String date1 = sdf.format(jDateChooser1.getDate());   
          //String date1 = date;
        
   //System.out.print(date1); 
   datos(date1);  
   
       // datos2(date1);
//System.out.print(date);
    //String formato = JDateChooser.getDefaultLocale().toString();
     
   //System.out.print(sdf); 
         
     
     //txtFechaSeleccionada.setText(sdf.format(date));
} catch(NullPointerException ex) {
     //JOptionPane.showMessageDialog(this, "Al menos selecciona una fecha válida!", "Error!", JOptionPane.INFORMATION_MESSAGE);
System.out.print("error"+ex);

}  
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

  
}
